POSITIVE_KEYWORDS = [
    "travel",
    "traveler",
    "travelling",
    "backpacking",
    "digital nomad",
    "airport",
    "flight",
    "visa",
    "trip",
    "hotel",
    "itinerary",
    "europe travel",
    "turkey travel",
    "esim",
    "roaming",
    "internet abroad",
    "data",
    "remote work",
    "expat",
    "budget travel",
    "solo travel",
    "family travel",
    "student travel",
]

NEGATIVE_KEYWORDS = [
    "crypto",
    "forex",
    "casino",
    "betting",
    "adult",
    "giveaway only",
    "meme only",
    "fake followers",
]

CONTACT_KEYWORDS = [
    "dm for collab",
    "collab",
    "partnership",
    "business",
    "brand deal",
    "sponsor",
    "sponsorship",
]

GEO_FIT_COUNTRIES = {
    "azerbaijan",
    "azerbaijan",
    "germany",
    "france",
    "italy",
    "spain",
    "netherlands",
    "poland",
    "georgia",
    "turkey",
    "turkiye",
    "united kingdom",
    "uk",
    "united states",
    "usa",
    "united arab emirates",
    "uae",
}

EU_COUNTRIES = {
    "austria",
    "belgium",
    "bulgaria",
    "croatia",
    "cyprus",
    "czech republic",
    "denmark",
    "estonia",
    "finland",
    "france",
    "germany",
    "greece",
    "hungary",
    "ireland",
    "italy",
    "latvia",
    "lithuania",
    "luxembourg",
    "malta",
    "netherlands",
    "poland",
    "portugal",
    "romania",
    "slovakia",
    "slovenia",
    "spain",
    "sweden",
}

